### PR TITLE
Issue/62

### LINKED ISSUE #63: Omeka Classic media source hardcodes insecure URL
in `system/application/rdf/omeka_to_json.php`, the given Omeka URL has its scheme stripped, and then `http://` prepended. If the Omeka installation is running over HTTPS, it is inaccessible to Scalar.

### PR DESCRIPTION
**Pull request by crism**
This adds support for Omeka S import (#62). Could be generalized to other JSON-LD sources if desired. Includes #65, which fixes #63, as a prerequisite.

### CODE REVIEW

**Comment by craigdietrich** [comment]
Fantastic, thanks!  I'll merge this up soon.

**Comment by crism** [comment]
@craigdietrich, this is the PR for #62, which also fixes #64. It includes the changes for #63 (PR #65).

**Comment by alexdryden** [comment]
Hi @craigdietrich, I was just following up on this pull request after testing this feature with the the most recent versions of Omeka-S and Scalar. I'm in the role @crism was in when this feature was developed.

**Comment by craigdietrich** [comment]
@alexdryden Hi! So, this pull request is ready to go? No testing or integration needed on our end?

Thanks!

**Comment by alexdryden** [comment]
Yeah, good to go @craigdietrich! We've used it with Omeka-S API 1.x and 2.x and I just tested with Scalar v2.5.12 and it works as expected.

Thanks!

**Comment by craigdietrich** [comment]
All set!

**Pull request merged**
