### PR TITLE
anvc/scalar#72: quote database name

### LINKED ISSUE #72: ARC triple store fails if DB name has a hyphen
```
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-sandbox
```
This is due to `ARC2_Store::createDBCon()` and possibly other places not quoting the database name.

### PR DESCRIPTION
**Pull request by crism**
Fixes #72. Tested on our hyphen-having sandbox.

### CODE REVIEW

**Comment by craigdietrich** [comment]
Whoa, this is great, thanks!

The one hiccup is that ARC2 is an external library https://github.com/semsol/arc2, but I've contributed to their repository before.  So I'm thinking you do a pull request with this there, then I go ahead and update ARC2 on Scalar (it's probably a good time to do that in any event).  What do you think @crism?

**Comment by crism** [comment]
I filed it as semsol/arc2#94 as well, after I’d already created this PR.

**Comment by craigdietrich** [comment]
Ah, okay! Did they merge the pull request there?  If not (like, if it'll take a while there) I'll go ahead and merge this at Scalar and we can worry about syncing things up later.

**Comment by k00ni** [comment]
Because i missed your discuss here, i "accidentally" created a fix with a basic test for ARC2_Store myself (https://github.com/semsol/arc2/pull/96). I hope it fully covers your case.

**Comment by crism** [comment]
Fantastic, @k00ni, thanks!

**Comment by craigdietrich** [comment]
Awesome. thanks @k00ni !  So, just to confirm, the Merge over on the arc2 repository includes the fix made here, which is adding MySQL quotes around the database name?

**Comment by craigdietrich** [comment]
Oh, I see ... over at arc2 they've Merged one but not the other, the other being the quotes DB name fix.

**Comment by k00ni** [comment]
> Oh, I see ... over at arc2 they've Merged one but not the other, the other being the quotes DB name fix.

I thought i added the quote-DB-name-fix to my pull request. 

https://github.com/semsol/arc2/commit/9db40c0a35dfb7b6feacb2b3d66e2c920bc2fca6#diff-3ad57ff8fd810858d6ad00eef07f4a91

What do you mean @craigdietrich?

**Pull request merged**
