### PR TITLE
IIIf integration

### PR DESCRIPTION
**Pull request by dodget**
This PR integrates mirador3 and IIIF functionality to scalar by:

- Adding a `Is IIIF` checkbox to forms in `system/application/views/melons/cantaloupe/upload.php` and `system/application/views/melons/cantaloupe/edit.php`
- Checking if the media is IIIF content during form validation, and appending `?iiif-manifest=1` to the end of the media url in `system/application/views/arbors/html5_RDFa/js/form-validation.js `
- Looking for `?iiif-manifest=1` in `system/application/controllers/api.php` and fetching/setting the relevant iiif metadata
- Adding a 'IIIF' mediaSource in `system/application/views/widgets/api/scalarapi.js`
- Add a `MiradorObjectView`; Checking if content is a manifest and invoking the `MiradorObjectView` in `system/application/views/widget/mediaelement/jquery.mediaelement.js`
- Building, minifying and including mirador 3 at `system/application/views/widgets/mediaelement/mirador.min.js`

The branch for this PR is based off of scalar v2.5.12. I'd be happy to update it with the latest changes from master if requested.

### CODE REVIEW

**Comment by eloyer** [comment]
@dodget Fantastic to see this up and running — thanks so much. Wondering if you might have any insight into why IIIF instances at small, medium, and large sizes are exceeding the vertical bounds of their container and overlapping the .mediaElementFooter element below? It's especially notable when you roll over the media; the whole instance expands vertically, when normally we'd expect the instance to remain fixed and the footer to expand.

**Comment by dodget** [comment]
Hm, that's not something that I observed, but I'll do some investigating and see if I can issue a fix. Thanks for the heads up @eloyer

**Comment by dodget** [comment]
It looks like I am going to have to set find a way to inherit a `max-height` on `#mirador-viewer`. I'll do my best to come up with a clean solution.

**Comment by eloyer** [comment]
@dodget Would you mind taking a look at an issue we've seen where two IIIF instances on a page will sometimes fail to load? [Here's an example.](https://scalar.usc.edu/dev/new-20th-cen-book/advanced-telephone-systsems) The issue is intermittent, but if it doesn't happen the first time it'll usually occur after one or two reloads.

**Comment by dodget** [comment]
Sure thing, I'll take a look when I get a chance.

**Comment by dodget** [comment]
Heads up @eloyer - I should have a fix coming for this early next week

**Comment by eloyer** [comment]
Excellent, thanks for the update @dodget !

**Pull request merged**
