### PR TITLE
Fix insert-problems on MySQL 5.6

### PR DESCRIPTION
**Pull request by burki**
Update CREATE TABLE statements with proper NULL-clauses and datetime-format in model-classes to be compatible with MySQL 5.6 settings (see #35, #36)

### CODE REVIEW

**Comment by craigdietrich** [comment]
Fantastic, thanks @burki!

A quick question, where does 'db_lang.php' come up?  Have you been getting error messages about this file not being found?

**Comment by burki** [comment]
I've got an error message for that file not being found and copied it over from system/language/english/db_lang.php. But I'm not sure if an empty file would be more appropriate?!

**Comment by craigdietrich** [comment]
Well it seems harmless to me.  I'm just not sure where CodeIgniter actually calls those error messages!   In any event, all looks good!

**Comment by craigdietrich** [comment]
PS, related, I'm slowly working on getting Scalar up to speed with PHP7....

**Pull request merged**
