### PR TITLE
Add ability to integrate authentication plugins

### PR DESCRIPTION
**Pull request by arthurian**
This PR adds the ability for a plugin to override the login form and provide an alternative authentication method besides email/password. 

It doesn't seem like there's an easy way to do this without hacking the core, so I've come up with a possible way forward that would allow an **auth** plugin to hook into the login/logout methods.

This approach takes advantage of the ability to remap controller methods on the fly using [_remap()](https://www.codeigniter.com/userguide2/general/controllers.html#remapping). The idea is that if an **auth** plugin is configured, it could hook into those methods and override or add functionality at that point. A more well-defined plugin system/interface would probably be preferable, but that seems like a much bigger task. 

We've developed and tested [scalar-plugin-casauth](https://github.com/harvard-atg/scalar-plugin-casauth) based on this approach, which adds CAS authentication to Scalar in addition to the default login method. 

**Technical Notes:**

- In order to make it possible to override login/logout in a more straightforward manner, I moved the authentication logic that was in the `MY_Controller` constructor to the system controller `login()` and `logout()` methods. This seems like a cleaner approach since it isolates that functionality better and makes it easier to hook into from the perspective of a plugin, but I'm wondering if I'm missing something. Is there a dependency on it being in the core constructor?
- The configuration assumes 0 or 1 auth plugin (not multiple plugins like the dashboard). 
- The auth plugin follows the basic pattern already established as far as 
 the path (`system/application/plugins/{plugin_name}/{plugin_name}_pi.php`).
- The auth plugin can override or extend the system controller by implementing methods that follow the pattern: `hook_system_{method}`. Examples:
    - `hook_system_login()`
    - `hook_system_logout()`
- No restrictions were placed on what methods the auth plugin can override, so in theory it could override any/all system methods and define any new ones that it needs. I didn't want to arbitrarily restrict what the plugin could do. 

Looking forward to thoughts, suggestions, and opinions about this change. 

Thanks!

### CODE REVIEW

**Comment by craigdietrich** [comment]
I start taking a look at this!

**Comment by WorksAtAUni** [comment]
I would find this useful...... honest to goodness.

**Comment by craigdietrich** [comment]
Sorry I haven't gotten to this sooner, there's a lot of changes in the Pull Request so want to do carefully.  I'll try to fast track it!

**Comment by arthurian** [comment]
@craigdietrich I just wanted to circle back to this PR and see if you were still considering these changes.

I noticed that there was a conflict related to the [google authenticator functionality](https://github.com/anvc/scalar/commit/20fc50eefc51add92011ea1a793586b37aceaceb), so I went ahead and resolved that. The conflict was in the controller constructor, which contained the logic for validating the POSTed authenticator code (e.g. via `do_google_authenticator`). Rather than validating it in the constructor, I moved it into the `authenticator` method, which is already rendering the view. This is similar to what I did before with the `login` method to render the view and validate the user credentials. Ultimately, this enables those methods to be remapped to support additional or alternative authentication, but shouldn't impact existing functionality in any way.

We've continued to use this successfully in our production instance to enable both username/password authentication as well as CAS authentication, so we are still interested in seeing this PR merged (in some form or another). If not, I would propose closing this PR rather than leaving it open indefinitely.

Thoughts?

**Comment by craigdietrich** [comment]
Hi @arthurian,

I went ahead and merged the commits.  Thanks for your work on this, appreciated!

**Pull request merged**
